Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.view_init(elev=20, azim=-55, roll=0)
ax.scatter(pt[0], pt[1], pt[2], color="r", s=100)
ax.text(pt[0]+2, pt[2]+1, pt[2]+1, pt, c='r')
ax.scatter(im[0], im[1], im[2], color="b", s=100)
ax.text(im[0]-2, im[1]-1, im[2]+2, im, c='b')
ax.axes.set_xlim3d(left=-5, right=5) 
ax.axes.set_ylim3d(bottom=-5, top=5) 
ax.axes.set_zlim3d(bottom=-5, top=5)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
vstring="{}i+{}j+{}k".format(axis[0],axis[1],axis[2])
arrow_prop_dict = dict(mutation_scale=20, arrowstyle='-|>', color='k', shrinkA=0, shrinkB=0, linewidth=2)
a = Arrow3D([0, 3*axis[0]], [0, 3*axis[1]], [0, 3*axis[2]], **arrow_prop_dict)
ax.text(0, 0, -2, vstring, c='k')
a2 = Arrow3D([pt[0], im[0]], [pt[1], im[1]], [pt[2], im[2]], mutation_scale=20,
            lw=1, arrowstyle="-|>", color="b", connectionstyle="arc3,rad=1", linestyle='--')

ax.add_artist(a)
ax.add_artist(a2)
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/9y/379gbxjx3255qz9rg64kh7mm0000gn/T/ipykernel_34598/4263899747.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mfig[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0mfigure[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0max[0m [0;34m=[0m [0mfig[0m[0;34m.[0m[0madd_subplot[0m[0;34m([0m[0;36m111[0m[0;34m,[0m [0mprojection[0m[0;34m=[0m[0;34m'3d'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0max[0m[0;34m.[0m[0mview_init[0m[0;34m([0m[0melev[0m[0;34m=[0m[0;36m20[0m[0;34m,[0m [0mazim[0m[0;34m=[0m[0;34m-[0m[0;36m55[0m[0;34m,[0m [0mroll[0m[0;34m=[0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0max[0m[0;34m.[0m[0mscatter[0m[0;34m([0m[0mpt[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mpt[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m,[0m [0mpt[0m[0;34m[[0m[0;36m2[0m[0;34m][0m[0;34m,[0m [0mcolor[0m[0;34m=[0m[0;34m"r"[0m[0;34m,[0m [0ms[0m[0;34m=[0m[0;36m100[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0max[0m[0;34m.[0m[0mtext[0m[0;34m([0m[0mpt[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m+[0m[0;36m2[0m[0;34m,[0m [0mpt[0m[0;34m[[0m[0;36m2[0m[0;34m][0m[0;34m+[0m[0;36m1[0m[0;34m,[0m [0mpt[0m[0;34m[[0m[0;36m2[0m[0;34m][0m[0;34m+[0m[0;36m1[0m[0;34m,[0m [0mpt[0m[0;34m,[0m [0mc[0m[0;34m=[0m[0;34m'r'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: view_init() got an unexpected keyword argument 'roll'
TypeError: view_init() got an unexpected keyword argument 'roll'

